---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  serial: 1 

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      notify: update_message

    - name: Upgrade system packages
      apt:
        upgrade: yes
        update_cache: yes
      notify: upgrade_message

    - name: Install prerequisites for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      notify: prerequisites_message

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository to Apt sources
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      notify: docker_repo_message

    - name: Update Apt package cache
      apt:
        update_cache: yes
      notify: update_message

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      notify: docker_install_message

    - name: Add host entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
      become: yes
      when: ansible_default_ipv4

  handlers:
    - name: update_message
      debug:
        msg: "Package cache updated."

    - name: upgrade_message
      debug:
        msg: "System packages upgraded."

    - name: prerequisites_message
      debug:
        msg: "Docker prerequisites installed."

    - name: docker_repo_message
      debug:
        msg: "Docker repository added to Apt sources."

    - name: docker_install_message
      debug:
        msg: "Docker installed successfully."
