---
- name: Docker Kurulumu
  hosts: all
  become: yes
  tasks:
    - name: Sistem Güncelleme ve Yükseltme
      apt:
        upgrade: dist
        update_cache: yes
    - name: ca-certificates ve curl paketlerini yükle
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: /etc/apt/keyrings dizinini oluştur
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Docker GPG anahtarını indir
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Docker APT deposunu ekle
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Paket listesini güncelle
      apt:
        update_cache: yes

    - name: Docker ve ilgili paketleri yükle
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Docker buildx eklentisini yükle
      shell: docker buildx install

    - name: Docker-compose eklentisini yükle
      shell: curl -sSL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
