apiVersion: v1
kind: Pod
metadata:
  name: pod_name   #change this
  labels:
    name: my-name  #change this
    app: my-app    #change this
spec:
  containers:
    - name: my-container
      image: my-image:latest # change this
      ports:
        - containerPort: 80
