apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset # change this
  labels:
    app: nginx # change this
spec:
  selector:
    matchLabels:
      app: nginx #change this
  template:
    metadata:
      labels:
        app: nginx #change this
    spec:
      containers:
      - name: nginx #change this
        image: nginx:latest # change this
        ports:
        - containerPort: 80
