apiVersion: v1
kind: Service
metadata:
  name: service_name #change this
spec:
  type: NodePort
  selector:
    app: my-app  #change this
    name: my-name #change this
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080 #change this
